<?php
return [
    'email_footer'               => 'Jangan membalas email apapun ke alamat email ini. Email ini dikirim secara otomatis oleh sistem kami. ',
    'login_message'              => 'Silahkan login untuk memulai sesi anda',
    'text_forgot_password'       => 'Lupa password ?',
    'page_title_login'           => 'Login Panel',
    'page_title_forgot'          => 'Lupa kata sandi',
    'forgot_message'             => 'Masukkan alamat email anda, untuk meminta password',
    "forgot_text_try_again"      => "Coba login lagi ?",
    'text_no_notification'       => "Anda memiliki 0 notifikasi",
    'text_view_all_notification' => 'Lihat semua',
    'label_button_profile'       => "Profil",
    'filter_dialog_title'        => 'Jenis lanjutan & Filter',

    'text_enter_the_password'     => 'Masukkan kata sandi Anda untuk mengambil sesi Anda',
    'text_or_sign_in'             => 'Atau masuk sebagai pengguna yang berbeda',
    'text_default_add_new_module' => 'Tambahkan Modul: Baru',
    'text_default_list_module'    => 'List :module',
    'text_default_help_password'  => 'Minimal 5 karakter. Biarkan kosong jika Anda tidak mengganti kata sandinya.',
    'text_default_help_upload'    => 'File types support : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number'    => 'Anda hanya bisa memasukkan nomor saja',
    'text_default_help_email'     => 'silakan isi alamat email',
    'text_default_help_text'      => 'Anda hanya bisa memasukkan huruf saja',
    'text_default_help_url'       => 'Masukkan URL yang valid',
    'text_dashboard'              => 'Dashboard',
    'text_prefix_option'          => '** Silahkan Pilih',
    'text_loading'                => 'Silahkan Tunggu untuk memulai...',

    'message_after_logout'    => 'Terima kasih, sampai jumpa lagi !',
    'message_forgot_password' => 'Kami telah mengirim kata sandi baru ke email Anda, check inbox atau spambox !',

    'page_not_found'      => 'Oops! Halaman tidak ditemukan',
    'page_not_found_text' => 'Kami tidak dapat mencari halaman yang anda cari.',
    'page_not_found_tips' => '* Pastikan URLnya sesuai<br/>
                * Pastikan font capitalizing sudah benar karena case sensitive<br/>
                * Mungkin halaman yang anda cari telah dihapus oleh Admin<br/>
                * Anda bisa kembali dengan mengklik Back Button di browser<br/>',

    'log_try_view'            => 'Coba lihat data: nama pada: modul',
    'log_try_edit'            => 'Coba edit data: nama di: module',
    'log_try_add'             => 'Coba tambahkan data pada: modul',
    'log_try_add_save'        => 'Coba tambahkan data: nama data di: module',
    'log_try_delete'          => 'Coba hapus: nama data di: modul',
    'log_try_delete_selected' => 'Coba hapus yang dipilih pada: modul',
    'log_try_delete_image'    => 'Coba hapus gambar dari: name data at: module',
    'log_try_update'          => 'Coba update: nama data di: module',
    'log_add'                 => 'Tambahkan Data Baru: nama pada: modul',
    'log_update'              => 'Update data: nama pada: modul',
    'log_delete'              => 'Hapus data: nama di: modul',
    'log_delete_image'        => 'Hapus gambar dari: nama di: module',
    'log_login'               => ':email login dengan IP Address :ip',
    'log_forgot'              => 'Seseorang dengan IP: ip meminta kata sandi untuk: email',
    'log_logout'              => ':email logout',

    'alert_delete_selected'         => 'Yakin ingin menghapus semua data yang dipilih ?',
    'alert_delete_selected_success' => 'Delete selected success !',
    'alert_action'                  => 'You have :action successfully !',
    'alert_add_data_success'        => 'Data telah ditambahkan !',
    'alert_add_data_failed'         => 'Failed to save the data !',
    'alert_update_data_success'     => 'The data has been updated !',
    'alert_update_data_failed'      => 'Failed to update the data',
    'alert_delete_data_success'     => 'Delete the data success !',
    'alert_want_to_logout'          => 'Apakah Anda ingin logout ?',
    'alert_warning'                 => "Oops",
    'alert_danger'                  => 'Ada yang salah ....',
    'alert_success'                 => 'Perubahan Ok ...',
    'alert_info'                    => 'Information',
    'alert_primary'                 => 'Information',
    'alert_session_expired'         => 'Sesi Anda telah habis masa berlakunya, harap masuk lagi!',
    'alert_password_wrong'          => 'Maafkan kata sandi anda salah !',
    'alert_required'                => 'Pastikan untuk mengisi semua bidang yang diperlukan dengan benar',
    'alert_error_ajax'              => 'Oke, ini memalukan, ada yang tidak beres, kita akan segera memperbaikinya !',
    'alert_validation_error'        => 'Silahkan isi formulir dengan benar : :error',

    'add_data_page_title'    => 'Tambah :module',
    'edit_data_page_title'   => 'Edit :module',
    'detail_data_page_title' => 'Detail :module',

    'default_module_description' => 'Data List',

    'delete_description_confirm' => "Anda tidak akan dapat memulihkan data rekam ini!",
    'delete_title_confirm'       => "Apakah kamu yakin ?",


    'action_show_data'       => 'Tampilkan Data',
    'action_add_data'        => 'Tambahkan Data',
    'action_delete_selected' => 'Hapus yang Dipilih',

    'action_label'       => 'Action',
    'action_detail_data' => 'Detail Data',
    'action_edit_data'   => 'Edit Data',
    'action_delete_data' => 'Delete',


    'button_cancel'          => 'Batal',
    'button_add'             => 'Add Data',
    'button_edit'            => 'Edit Data',
    'button_back'            => 'Kembali',
    'button_save'            => 'Simpan',
    'button_save_more'       => 'Simpan & Tambahkan lagi',
    'button_import'          => 'Import Data',
    'button_export'          => 'Export Data',
    'button_filter'          => 'Sort & Filter',
    'button_close'           => 'Tutup',
    'button_submit'          => 'Kirim',
    'button_logout'          => 'Logout',
    'button_sign_in'         => 'Masuk',
    'button_selected_action' => 'Bulk Actions',
    'button_download_file'   => 'Download file',
    'button_reset'           => 'Reset',

    'export_dialog_title'            => "Export Data",
    'export_dialog_filename'         => 'File Name',
    'export_dialog_help_filename'    => 'Anda dapat mengganti nama nama file sesuai dengan keinginan Anda',
    'export_dialog_maxdata'          => "Max Data",
    'export_dialog_help_maxdata'     => 'Minimum 1 and maximum 100,000 rows per export session',
    'export_dialog_columns'          => 'Columns',
    'export_dialog_format_export'    => 'Format Export',
    'export_dialog_show_advanced'    => 'Show Advanced Export',
    'export_dialog_page_size'        => 'Ukuran Halaman',
    'export_dialog_set_default'      => 'Set Sesuai Ukuran Kertas',
    'export_dialog_page_orientation' => 'Orientasi Halaman',

    'import_page_title'         => 'Import Data :module',
    'dashboard_default_text'    => 'Selamat datang di dashboard  :appname',
    'form_back_to_list'         => 'Kembali ke List Data :module',
    'not_logged_in'             => 'Anda belum login !',
    'menu_navigation'           => "Navigasi",
    'table_data_not_found'      => "Tidak ada Data Tersedia",
    "notice_delete_file_upload" => "* Jika ingin mengunggah file lain, pertama-tama hapus file tersebut.",
    "file_broken"               => "Ups sepertinya File itu Rusak! Klik Hapus dan Upload Ulang.",

    'denied_access' => 'Maaf, Anda tidak memiliki hak istimewa untuk melakukan akses pada area ini !',
    'denied_update' => 'Maaf, Anda tidak memiliki hak istimewa untuk melakukan untuk update data !',
    'denied_create' => 'Maaf, Anda tidak memiliki hak istimewa untuk melakukan pembuatan data !',
    'denied_delete' => 'Maaf, Anda tidak memiliki hak istimewa untuk melakukan untuk menghapus data !',

    'user_image'           => 'User Image',
    'online'               => 'Online',
    'controller_route_404' => 'Controller / Route Not Found',
    'home'                 => 'Home',

    'Privileges_Roles'    => 'Privileges Roles',
    'Add_New_Privilege'   => 'Tambahkan Privilege Baru',
    'List_Privilege'      => 'List Privilege',
    'add_user'            => 'Tambahkan User',
    'List_users'          => 'List Users',
    'Menu_Management'     => 'Menu Management',
    'Add_New_Setting'     => 'Tambahkan Setting Baru',
    'Add_New_Module'      => 'Tambahkan Modul Baru',
    'List_Module'         => 'List Modul',
    'Add_New_Statistic'   => 'Tambahkan Statistic Baru',
    'List_Statistic'      => 'List Statistic',
    'Add_New_API'         => 'Tambahkan API Baru',
    'API_Generator'       => 'API Generator',
    'Statistic_Builder'   => 'Pembuatan Statistic',
    'Module_Generator'    => 'Modul Generator',
    'settings'            => 'Settings',
    'Users_Management'    => 'Users Management',
    'list_API'            => 'List API (Dokumentasi)',
    'Generate_Screet_Key' => 'Generate Kunci Rahasia',
    'Add_New_Email'       => 'Tambahkan Email Baru',
    'List_Email_Template' => 'List Email Template',
    'Email_Templates'     => 'Email Templates',
    'Log_User_Access'     => 'Log Hak Akses User',
    'SUPERADMIN'          => 'SUPERADMIN',

    'click_here' => 'Klik Disini',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right'      => 'Kanan',
    'left'       => 'Kiri',

    'all_rights_reserved' => 'All Rights Reserved',
    'copyright'           => 'Copyright',
    'powered_by'          => 'Powered by',

    'notification_you_have'     => 'Anda Mempunyai',
    'notification_notification' => 'Notifikasi',
    'notification_new'          => 'Anda mempunyai notifikasi baru !',

    'login_register_style'         => 'Style Pendaftaran Login',
    'email_setting'                => 'Setting Email',
    'application_setting'          => 'Application Setting',

    // table filter & sort 
    'filter_select_operator_type'  => 'Pilih Tipe Operator',
    'filter_ascending'             => 'ASCENDING',
    'filter_descending'            => 'DESCENDING',
    'filter_equal_to'              => '=(Equal to)',
    'filter_like'                  => 'LIKE',
    'filter_not_like'              => 'NOT LIKE',
    'filter_greater_than_or_equal' => '>= (Greater Than or Equal)',
    'filter_less_than_or_equal'    => '<= (Less Than or Equal)',
    'filter_less_than'             => '< (Less Than)',
    'filter_greater_than'          => '> (Greater Than)',
    'filter_not_equal_to'          => '!= (Not Equal to)',
    'filter_in'                    => 'IN',
    'filter_not_in'                => 'NOT IN',
    'filter_between'               => 'BETWEEN',
    'filter_sort_ascending'        => 'Sort ascending',
    'filter_sort_descending'       => 'Sort Descending',
    'filter_eg'                    => 'e.g',
    'filter_lorem_ipsum'           => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search'                => 'Pencarian',
    'filter_from'                  => 'Dari',
    'filter_to'                    => 'Kepada',

    // confirmation
    'confirmation_yes'             => 'Ya!',
    'confirmation_no'              => 'Tidak',

    //filemanager
    'chose_an_image'               => 'Pilih Gambar ',
    'chose_an_file'                => 'Pilih file ',

];
